# Railway.app Deployment Configuration
# This file configures your service on Railway

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python api_server.py"
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"

[env]
PORT = "8000"
HOST = "0.0.0.0"
PYTHON_VERSION = "3.11.9"
