# Render.com deployment configuration - Updated for Python 3.13 compatibility
services:
  - type: web
    name: insure-info-hackathon-api
    env: python
    buildCommand: ./build.sh
    startCommand: python api_server.py
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /health
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_API_KEY_2
        sync: false
      - key: GOOGLE_API_KEY_3
        sync: false
      - key: GOOGLE_API_KEY_4
        sync: false
      - key: PORT
        value: "8000"
      - key: HOST
        value: "0.0.0.0"
    autoDeploy: true
